version: '2'
services:
  db:
    restart: always
    image: postgres
    volumes_from:
      - data
    depends_on:
      - data
  data:
    restart: always
    image: postgres
    volumes:
      - /var/lib/postgresql
    command: "true"
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /workspace/src/static/
      - ./nginx/log:/var/log/
    volumes_from:
      - web:rw
    links:
      - web:web
    depends_on:
      - web
  web:
    restart: always
    build: .
    expose:
      - "8000"
    env_file:
      - .env
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ./webapp:/workspace
    depends_on:
      - db